services:
  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./back/.env.dev

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web

