services:
  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./back/.env.dev
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_test
      - POSTGRES_PASSWORD=django_test
      - POSTGRES_DB=django_test

volumes:
  postgres_data:
